services:

  db:
    image: postgres:16
    container_name: leffa-db
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./LeffaAppiDb.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    container_name: leffa-api
    env_file:
      - ./.env
    ports:
      - "${API_PORT}:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: leffa-frontend
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - api

volumes:
  pgdata: