services:
  - type: web
    name: leffa-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: VITE_API_URL
        value: https://leffa-api.onrender.com

  - type: web
    name: leffa-api
    env: docker
    rootDir: api
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leffa-db
          property: connectionString

databases:
  - name: leffa-db
    plan: free