services:
  - type: web
    name: leffa-frontend
    env: docker
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: VITE_API_URL

  - type: web
    name: leffa-appi
    env: docker
    rootDir: ./api
    dockerfilePath: ./api/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leffa-db
          property: connectionString

databases:
  - name: leffa-db
    plan: starter